services:
  # Frontend React
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - ./Frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - app-network
  # Backend Node.js
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - app-network
  # Base de Datos PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./Backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local