services:
  # Frontend React
  frontend:
    build:
      context: ./libreria-react
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - libreria-react/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./libreria-react:/app
      - /app/node_modules
    networks:
      - app-network
  # Backend Node.js
  backend:
    build:
      context: ./libreria-api
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - ./libreria-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./libreria-api:/app
      - /app/node_modules
    networks:
      - app-network
  # Base de Datos PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./libreria-api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./libreria-api/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local